import '../styles/globals.css'
import { useEffect, useState } from 'react';
import { SessionProvider } from "next-auth/react"
import Header from '../Component/Header';
import Head from 'next/head';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Footer from '../Component/Footer';
import Context from '../Component/Context';
export default function App({ Component,session, pageProps }) {
  const [showChild, setShowChild] = useState(false);
  useEffect(() => {
    setShowChild(true);
  }, []);

  if (!showChild) {
    return null;
  }
  return <>
  <Head>
        
        <title>Buy One Get One</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          {/* tailwind-css */}
          <link href="/dist/output.css" rel="stylesheet"/>
          <style> @import url('https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Roboto:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap'); </style>
          <script src="https://cdn.tailwindcss.com"></script>
         <link href="https://cdn.jsdelivr.net/npm/daisyui@2.33.0/dist/full.css" rel="stylesheet" type="text/css" />

        </Head>
        <Context>
        <SessionProvider session={session}>
      <ToastContainer autoClose={500} />
     <Header></Header>
    <Component {...pageProps} />
    <Footer></Footer>
  </SessionProvider>
        </Context>
  </>
}
